# .env environment file should define
# ENGINE_API_KEY
# GOOGLE_CLIENT_ID
# GOOGLE_CLIENT_SECRET
# FACEBOOK_APP_ID
# FACEBOOK_APP_SECRET
# RECAPTCHA_SECRET
version: '3.7'
services:
  wright-node:
    image: jhanschoo/writerite-wright-node:0.1.0-dev1
    restart: always
    env_file: .env
    environment:
      # see https://stackoverflow.com/questions/29283040/how-to-add-custom-certificate-authority-ca-to-nodejs
      CA_CERT_FILE: /run/secrets/https_ca_cert
      GRAPHQL_HTTP: https://backend-apollo:4000/graphql
      REDIS_HOST: redis
      REDIS_PORT: '6379'
    secrets:
      - https_ca_cert
  backend-apollo:
    image: jhanschoo/writerite-backend-apollo:0.1.0-dev1
    restart: always
    ports:
      - '4000:4000'
    env_file: .env
    environment:
      PRISMA_ENDPOINT: http://prisma:4466/writerite/development
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      CERT_FILE: /run/secrets/https_cert
      KEY_FILE: /run/secrets/https_key
    secrets:
      - https_cert
      - https_key
  redis:
    image: redis:5.0.5-alpine
    restart: always
    stop_grace_period: 1m
    ports:
      - '6379:6379'
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    stop_grace_period: 1m
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            user: prisma
            password: prisma
            rawAccess: true
            port: 5432
            migrations: true
  postgres:
    image: postgres:11.5-alpine
    restart: always
    stop_grace_period: 1m
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: null
secrets:
  https_cert:
    file: pki/wr-dev.secp256r1.crt
  https_ca_cert:
    file: pki/wr-dev.secp256r1.ca.crt
  https_key:
    file: pki/wr-dev.secp256r1.private
