
projects:
  writerite-backend-apollo:
    schemaPath: schema.graphql
    extensions:
      endpoints:
        dev: http://localhost:4000
  prisma:
    schemaPath: generated/prisma.graphql
    extensions:
      prisma: prisma.yml
