
projects:
  writerite-backend-yoga:
    schemaPath: src/schema/schema.graphql
    extensions:
      endpoints:
        dev: http://localhost:4000
  prisma:
    schemaPath: generated/prisma.graphql
    extensions:
      prisma: prisma.yml
