default:
  image: docker:19.03.2
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"

build-backend-apollo:
  stage: build
  script:
    - docker info
  services:
    - docker:19.03.2-dind