default:
  image: docker:19.03

stages:
  - check-versions
  - publish-api-dev
  - build-services
  - build-clients
  # - deploy

variables:
  # secrets configured in UI/API:
  # - APOLLO_KEY
  # - K8S_SECRET_ENGINE_API_KEY
  # - KUBERNETES_VERSION
  # - HELM_VERSION
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

publish-api-dev:
  stage: publish-api-dev
  image: node
  before_script: []
  script:
    - cd backend-apollo
    - npm i -g apollo
    - apollo service:push --graph=writerite-2020-04-24 --key=$APOLLO_KEY --variant=tmp --localSchemaFile=schema.graphql
