default:
  image: docker:19.03.2

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

build-backend-apollo:
  stage: build
  script:
    - apk add --update nodejs nodejs-npm zsh
    - docker info
  services:
    - docker:19.03.2-dind
    - prismagraphql/prisma:1.34
    - postgres:11.2