default:
  image: docker:19.03.2

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  PRISMA_CONFIG: |
    port: 4466
    databases:
      default:
        connector: postgres
        host: postgres
        port: 5432
        user: prisma
        password: prisma
build-backend-apollo:
  stage: build
  script:
    - apk add --update nodejs npm zsh python2
    - docker run -p 4466:4466 -e "$PRISMA_CONFIG" prismagraphql/prisma:1.34
    # - zsh backend-apollo/ci.sh
  # note that prisma cannot be run as a service due to
  # https://gitlab.com/gitlab-org/gitlab-runner/issues/1042
  services:
    - docker:19.03.2-dind
    - postgres:11.5
