default:
  image: docker:19.03.2

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  PRISMA_CONFIG: |
    port: 4466
    databases:
      default:
        connector: postgres
        host: localhost
        port: 5432
        user: postgres
        password: postgres
build-backend-apollo:
  stage: build
  script:
    - docker run -p 5432:5432 -e POSTGRES_USER -e POSTGRES_PASSWORD prismagraphql/prisma:1.34
    - docker run -p 4466:4466 -e PRISMA_CONFIG prismagraphql/prisma:1.34
    - apk add --update nodejs npm zsh python2 make gcc
    - cd backend-apollo
    - ls
    - npm install
  # note that prisma cannot be run as a service due to
  # https://gitlab.com/gitlab-org/gitlab-runner/issues/1042
  services:
    - docker:19.03.2-dind
    # - postgres:11.5
