version: "3"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - writerite_dev_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - writerite_dev_network
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  writerite_dev_network:
volumes:
  postgres_data:
