apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "writerite-apiserver.fullname" . }}
  labels:
    {{- include "writerite-apiserver.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "writerite-apiserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "writerite-apiserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "writerite-apiserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "{{ .Chart.Name }}-app"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.appImage.repository }}:{{ .Values.appImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.appImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "writerite-apiserver.fullname" . }}
                  key: databaseUrl
                  optional: false
            - name: FACEBOOK_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "writerite-apiserver.fullname" . }}
                  key: facebookAppId
                  optional: false
            - name: FACEBOOK_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "writerite-apiserver.fullname" . }}
                  key: facebookAppSecret
                  optional: false
            - name: GAPI_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "writerite-apiserver.fullname" . }}
                  key: gapiClientId
                  optional: false
            - name: GAPI_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "writerite-apiserver.fullname" . }}
                  key: gapiClientSecret
                  optional: false
            - name: GRAPHQL_HTTP
              valueFrom:
                secretKeyRef:
                  name: {{ include "writerite-apiserver.fullname" . }}
                  key: graphqlHttp
                  optional: false
            - name: GRAPHQL_WS
              valueFrom:
                secretKeyRef:
                  name: {{ include "writerite-apiserver.fullname" . }}
                  key: graphqlWs
                  optional: false
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "writerite-apiserver.fullname" . }}
                  key: jwtPrivateKey
                  optional: false
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "writerite-apiserver.fullname" . }}
                  key: jwtPublicKey
                  optional: false
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: {{ include "writerite-apiserver.fullname" . }}
                  key: nodeEnv
                  optional: false
            - name: RECAPTCHA_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "writerite-apiserver.fullname" . }}
                  key: recaptchaClientKey
                  optional: false
            - name: RECAPTCHA_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "writerite-apiserver.fullname" . }}
                  key: recaptchaSecret
                  optional: false
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "writerite-apiserver.fullname" . }}
                  key: redisHost
                  optional: false
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "writerite-apiserver.fullname" . }}
                  key: redisPort
                  optional: false
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "writerite-apiserver.fullname" . }}
                  key: redisPassword
                  optional: false
            - name: WRIGHT_SECRET_JWT
              valueFrom:
                secretKeyRef:
                  name: {{ include "writerite-apiserver.fullname" . }}
                  key: wrightSecretJwt
                  optional: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
