apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: letsencrypt
  namespace: writerite-10694983-production
spec:
  secretName: letsencrypt-tls
  issuerRef:
    name: letsencrypt
  dnsNames:
    - api.writerite.site
    - "*.api.writerite.site"