apiVersion: v1
kind: Secret
metadata:
  name: {{ include "writerite-wright-node.fullname" . }}
  labels:
{{ include "writerite-wright-node.labels" . | indent 4 }}
type: Opaque
data:
  graphqlHttp: {{ .Values.graphql.http | b64enc | quote }}
  graphqlWs: {{ .Values.graphql.ws | b64enc | quote }}
  wrightSecretJwt: {{ .Values.wrightSecretJwt | b64enc | quote }}
