apiVersion: v1
kind: Service
metadata:
  name: redis-debug
  labels:
    app: redis
    env: debug
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    env: production
    tier: backend
  type: LoadBalancer