kubectl apply -f kubernetes/postgres.deployment.yaml
kubectl apply -f kubernetes/postgres.pvc.yaml
kubectl apply -f kubernetes/postgres.service.yaml
kubectl apply -f kubernetes/prisma.deployment.yaml
kubectl apply -f kubernetes/prisma.service.yaml
kubectl apply -f kubernetes/redis.deployment.yaml
kubectl apply -f kubernetes/redis.service.yaml
kubectl apply -f kubernetes/writerite-backend-yoga.deployment.yaml
kubectl apply -f kubernetes/writerite-backend-yoga.service.yaml
kubectl apply -f kubernetes-development/writerite-development.ingress.yaml
