apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    env: production
    tier: backend
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
    env: production
    tier: backend
