apiVersion: v1
kind: Service
metadata:
  name: prisma-debug
  labels:
    app: prisma
    env: debug
    tier: backend
spec:
  ports:
  - port: 4466
    targetPort: 4466
  selector:
    app: prisma
    env: production
    tier: backend
  type: LoadBalancer