apiVersion: v1
kind: Service
metadata:
  name: writerite-backend-yoga-debug
  labels:
    app: writerite-backend-yoga
    env: debug
    tier: backend
spec:
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: writerite-backend-yoga
    env: production
    tier: backend
  type: LoadBalancer