apiVersion: v1
kind: Secret
metadata:
  name: {{ include "writerite-backend-apollo.fullname" . }}
  labels:
{{ include "writerite-backend-apollo.labels" . | indent 4 }}
type: Opaque
data:
  apolloKey: {{ .Values.apolloKey | b64enc | quote }}
  databaseUrl: {{ printf "postgresql://%s:%s@%s:%s/%s" .Values.database.user .Values.database.password .Values.database.host .Values.database.port .Values.database.database | b64enc | quote }}
  redisHost: {{ .Values.redis.host | b64enc | quote }}
  redisPort: {{ .Values.redis.port | b64enc | quote }}
  googleClientId: {{ .Values.googleClient.id | b64enc | quote }}
  googleClientSecret: {{ .Values.googleClient.secret | b64enc | quote }}
  facebookAppId: {{ .Values.facebookApp.id | b64enc | quote }}
  facebookAppSecret: {{ .Values.facebookApp.secret | b64enc | quote }}
  recaptchaSecret: {{ .Values.recaptcha.secret | b64enc | quote }}
