apiVersion: v1
kind: Secret
metadata:
  name: {{ include "writerite-backend-apollo.fullname" . }}
  labels:
{{ include "writerite-backend-apollo.labels" . | indent 4 }}
type: Opaque
data:
  engineApiKey: {{ .Values.engineApiKey | b64enc | quote }}
  facebookAppId: {{ .Values.facebookAppId | b64enc | quote }}
  facebookAppSecret: {{ .Values.facebookAppSecret | b64enc | quote }}
  googleClientId: {{ .Values.googleClientId | b64enc | quote }}
  googleClientSecret: {{ .Values.googleClientSecret | b64enc | quote }}
  recaptchaSecret: {{ .Values.recaptchaSecret | b64enc | quote }}
