apiVersion: v1
kind: Secret
metadata:
  name: {{ include "writerite-backend-apollo.fullname" . }}
  labels:
{{ include "writerite-backend-apollo.labels" . | indent 4 }}
type: Opaque
data:
  apolloGraphId: {{ .Values.apollo.graphId | b64enc | quote }}
  apolloGraphVariant: {{ .Values.apollo.graphVariant | b64enc | quote }}
  apolloKey: {{ .Values.apollo.key | b64enc | quote }}
  apolloSchemaReporting: {{ .Values.apollo.schemaReporting | b64enc | quote }}
  databaseUrl: {{ printf "postgresql://%s:%s@%s:%s/%s" .Values.database.user .Values.database.password .Values.database.host .Values.database.port .Values.database.database | b64enc | quote }}
  facebookAppId: {{ .Values.facebookApp.id | b64enc | quote }}
  facebookAppSecret: {{ .Values.facebookApp.secret | b64enc | quote }}
  gapiClientId: {{ .Values.gapiClient.id | b64enc | quote }}
  gapiClientSecret: {{ .Values.gapiClient.secret | b64enc | quote }}
  graphqlHttp: {{ .Values.graphql.http | b64enc | quote }}
  graphqlWs: {{ .Values.graphql.ws | b64enc | quote }}
  jwtPrivateKey: {{ .Values.jwt.privateKey | b64enc | quote }}
  jwtPublicKey: {{ .Values.jwt.publicKey | b64enc | quote }}
  recaptchaClientKey: {{ .Values.recaptcha.clientKey | b64enc | quote }}
  recaptchaSecret: {{ .Values.recaptcha.secret | b64enc | quote }}
  redisHost: {{ .Values.redis.host | b64enc | quote }}
  redisPort: {{ .Values.redis.port | b64enc | quote }}
  redisPassword: {{ .Values.redis.password | b64enc | quote }}
  wrightSecretJwt: {{ .Values.wrightSecretJwt | b64enc | quote }}
