apiVersion: apps/v1
kind: Deployment
metadata:
  name: prisma
spec:
  selector:
    matchLabels:
      app: prisma
      env: production
      tier: backend
  template:
    metadata:
      labels:
        app: prisma
        env: production
        tier: backend
    spec:
      containers:
      - env:
        - name: PRISMA_CONFIG
          value: |
            port: 4466
            managementApiSecret: writerite-prisma
            databases:
              default:
                connector: postgres
                host: postgres
                port: 5432
                user: prisma
                password: prisma
        image: prismagraphql/prisma:1.31
        name: prisma
        ports:
        - containerPort: 4466
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
