apiVersion: v1
kind: Service
metadata:
  name: writerite-backend-yoga
  labels:
    app: writerite-backend-yoga
    env: production
    tier: backend
spec:
  ports:
  - port: 4000
    targetPort: 4000
  type: NodePort
  selector:
    app: writerite-backend-yoga
    env: production
    tier: backend
