apiVersion: v1
kind: Service
metadata:
  name: writerite-backend-apollo
  labels:
    app: writerite-backend-apollo
    env: production
    tier: backend
spec:
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP
  selector:
    app: writerite-backend-apollo
    env: production
    tier: backend
