# Default values for writerite-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

redis:
  architecture: standalone
  master:
    persistence:
      enabled: false
  auth:
    password: writerite
postgresql:
  auth:
    username: writerite
    password: writerite
    database: writerite
writerite-apiserver:
  database:
    user: writerite
    password: writerite
    database: writerite
  redis:
    password: writerite