# Default values for writerite-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

redis:
  architecture: standalone
  master:
    persistence:
      enabled: false
