# Default values for writerite-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

redis:
  cluster:
    enabled: false
  master:
    persistence:
      enabled: false
  networkPolicy:
    enabled: false
  usePassword: false
